version: '3'

services:
    api: 
        container_name: api-books-dock
        restart: always
        build: .
        ports:
            - 3000:4000
    
    mongo:
        container_name: mongoDB
        image: mongo
        ports:
            - 27022:27017